pgm
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             SETASPGRP  ASPGRP(IASP01)
             /* riga aggiunta alle 17 e 59 */
